#!/bin/bash
while TRUE
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
echo "Loading.."
sleep .001
echo "Loading..."
sleep .001
echo "Loading...."
sleep .001
echo "Loading....."
sleep .001
echo "Loading......"
sleep .001
echo "Loading......."
sleep .001
echo "Loading........"
sleep .001
echo "Loading........."
sleep .001
echo "Loading.........."
sleep .001
